general:
  playerBaseHP: 20.0
  defaultLanguage: enUs
  allowCustomExplosions: true
  allowBuild: true
  allowPvP: true
  allowHurtAnimals: true
  saveStatsTimer: 900
multipliers:
  globalMultiplier: 1.0
  diggingMultiplier: 1.0
  woodcuttingMultiplier: 1.0
  miningMultiplier: 1.0
  farmingMultiplier: 1.0
  fishingMultiplier: 1.0
  archeryMultiplier: 1.0
  beastMasteryMultiplier: 1.0
  swordsmanshipMultiplier: 1.0
  defenseMultiplier: 1.0
  axeMasteryMultiplier: 1.0
  repairMultiplier: 1.0
  agilityMultiplier: 1.0
  alchemyMultiplier: 1.0
  smeltingMultiplier: 1.0
  enchantingMultiplier: 1.0
tokens:
  automaticPassiveUpgradesPerLevel: 1.0
  levelsPerPassiveToken: 1.0
  levelPerSkillToken: 100.0
  levelsPerGlobalToken: 1000.0
  startingPassiveTokens: 0
  startingSkillTokens: 0
  startingGlobalTokens: 0
souls:
  startingSouls: 0
  refundCost: 250
leveling:
  maxLevel: -1
  exponentialGrowthFactor: 1.001595
  exponentialReferenceLevel: 1000
  exponentialReferenceEXP: 10000000.0
  levelBeginLinear: 1000
  LinearEXPperLevel: 20000.0
digging:
  maxLevel: -1
  drops:
    drop1Name: glowstone_dust
    drop1Amount: 1
    drop2Name: gold_nugget
    drop2Amount: 1
    drop3Name: string
    drop3Amount: 1
    drop4Name: iron_nugget
    drop4Amount: 1
    drop5Name: cobweb
    drop5Amount: 1
    drop6Name: gold_ingot
    drop6Amount: 1
    drop7Name: name_tag
    drop7Amount: 1
    drop8Name: music_disc_null
    drop8Amount: 1
    drop9Name: horse_armor_null
    drop9Amount: 1
    drop10Name: diamond
    drop10Amount: 1
    drop10BaseChance: 0.0025
    drop11Name: emerald
    drop11Amount: 1
    drop11BaseChance: 0.00229
    drop12Name: enchanted_book
    drop12Amount: 1
    drop12BaseChance: 0.001275
    drop13Name: dragon_breath
    drop13Amount: 1
    drop13BaseChance: 0.00835
    drop14Name: totem_of_undying
    drop14Amount: 1
    drop14BaseChance: 0.0025
    drop15Name: nether_star
    drop15Amount: 1
    drop15BaseChance: 0.001
woodcutting:
  maxLevel: -1
  drops:
    leavesDrop1Name: feather
    leavesDrop1Amount: 1
    leavesDrop1Chance: 0.02
    leavesDrop2Name: gold_nugget
    leavesDrop2Amount: 1
    leavesDrop2Chance: 0.02
    leavesDrop3Name: golden_apple
    leavesDrop3Amount: 1
    leavesDrop3Chance: 0.0025
    leavesDrop4Name: experience_bottle
    leavesDrop4Amount: 1
    leavesDrop4Chance: 0.0075
    leavesDrop5Name: enchanted_golden_apple
    leavesDrop5Amount: 1
    leavesDrop5Chance: 0.0005
mining:
  maxLevel: -1
farming:
  maxLevel: -1
fishing:
  maxLevel: -1
  drops:
    tier1_baseChance: 0.045
    tier2_baseChance: 0.025
    tier3_baseChance: 0.015
    tier4_baseChance: 0.010
    tier5_baseChance: 0.005
    tier1_drop1Name: ender_pearl
    tier1_drop1Amount: 1
    tier1_drop1Random: 0
    tier1_drop1Name_HotRod: fire_charge
    tier1_drop1Amount_HotRod: 3
    tier1_drop1Random_HotRod: 0
    tier1_drop2Name: ghast_tear
    tier1_drop2Amount: 1
    tier1_drop2Random: 0
    tier1_drop2Name_HotRod: blaze_powder
    tier1_drop2Amount_HotRod: 1
    tier1_drop2Random_HotRod: 0
    tier1_drop3Name: gold_ingot
    tier1_drop3Amount: 1
    tier1_drop3Random: 0
    tier1_drop4Name: iron_ingot
    tier1_drop4Amount: 1
    tier1_drop4Random: 0
    tier1_enchantedArmor: 1
    tier2_drop1Name: wet_sponge
    tier2_drop1Amount: 3
    tier2_drop1Random: 0
    tier2_drop1Name_HotRod: sponge
    tier2_drop1Amount_HotRod: 1
    tier2_drop1Random_HotRod: 0
    tier2_drop2Name: emerald
    tier2_drop2Amount: 1
    tier2_drop2Random: 0
    tier2_drop3Name: slime_ball
    tier2_drop3Amount: 1
    tier2_drop3Random: 0
    tier2_drop3Name_HotRod: magma_cream
    tier2_drop3Amount_HotRod: 1
    tier2_drop3Random_HotRod: 0
    tier2_drop4Name: ender_pearl
    tier2_drop4Amount: 2
    tier2_drop4Random: 3
    tier2_drop4Name_HotRod: fire_charge
    tier2_drop4Amount_HotRod: 2
    tier2_drop4Random_HotRod: 3
    tier2_enchantedArmor: 1
    tier3_drop1Name: music_disc_null
    tier3_drop1Amount: 1
    tier3_drop1Random: 0
    tier3_drop2Name: spectral_arrow
    tier3_drop2Amount: 5
    tier3_drop2Random: 10
    tier3_drop3Name: chainmail_null
    tier3_drop3Amount: 1
    tier3_drop3Random: 0
    tier3_drop4Name: trident
    tier3_drop4Amount: 1
    tier3_drop4Random: 0
    tier3_enchantedArmor: 1
    tier4_drop1Name: diamond
    tier4_drop1Amount: 1
    tier4_drop1Random: 0
    tier4_drop2Name: nautilus_shell
    tier4_drop2Amount: 2
    tier4_drop2Random: 2
    tier4_drop3Name: emerald
    tier4_drop3Amount: 3
    tier4_drop3Random: 5
    tier4_drop4Name: crossbow_enchanted_null
    tier4_drop4Amount: 1
    tier4_drop4Random: 0
    tier4_enchantedArmor: 1
    tier5_drop1Name: elytra
    tier5_drop1Amount: 1
    tier5_drop1Random: 0
    tier5_drop2Name: heart_of_the_sea
    tier5_drop2Amount: 1
    tier5_drop2Random: 0
    tier5_drop3Name: totem_of_undying
    tier5_drop3Amount: 1
    tier5_drop3Random: 0
    tier5_drop4Name: diamond
    tier5_drop4Amount: 1
    tier5_drop4Random: 0
    tier5_enchantedArmor: 1
archery:
  maxLevel: -1
beastMastery:
  maxLevel: -1
swordsmanship:
  maxLevel: -1
defense:
  maxLevel: -1
axeMastery:
  maxLevel: -1
repair:
  maxLevel: -1
agility:
  maxLevel: -1
alchemy:
  maxLevel: -1
smelting:
  maxLevel: -1
enchanting:
  maxLevel: -1



