name: FreeRPG
version: ${project.version}
main: mc.carlton.freerpg.FreeRPG
api-version: 1.13
authors: [JackCarlton]
description: Made from Spite
commands:
  frpg:
    description: Main FreeRPG command, type /frpg help for more info
    aliases: [freeRPG]
  spite:
    descriptions: Tells you what spite is good for.
permissions:
  freeRPG.*:
    description: Gives access to all freeRPG commands
    default: op
    children:
      freeRPG.mainGUI: true
      freeRPG.configGUI: true
      freeRPG.craftGUI: true
      freeRPG.confirmGUI: true
      freeRPG.skillsGUI: true
      freeRPG.info: true
      freeRPG.help: true
      freeRPG.enchantItem: true
      freeRPG.leaderboard: true
      freeRPG.giveEXP: true
      freeRPG.setLevel: true
      freeRPG.statReset: true
  freeRPG.standardPlayer:
    description: Grants the player all recommended permissions (for a common player)
    default: true
    children:
      freeRPG.GUI: true
      freeRPG.getEXP: true
      freeRPG.useAbilites: true
      freeRPG.canRepair: true
      freeRPG.canSalvage: true
      freeRPG.fish: true
  freeRPG.GUI:
    description: Gives access to all GUI commands
    default: true
    children:
      freeRPG.mainGUI: true
      freeRPG.configGUI: true
      freeRPG.craftGUI: true
      freeRPG.confirmGUI: true
      freeRPG.skillsGUI: true
  freeRPG.changeStats:
    description: Gives access to all stat changing commands
    default: op
    children:
      freeRPG.giveEXP: true
      freeRPG.setLevel: true
      freeRPG.statReset: true
  freeRPG.getEXP:
    description: Allows player to gain every type of EXP
    default: true
    children:
      freeRPG.diggingEXP: true
      freeRPG.woodcuttingEXP: true
      freeRPG.miningEXP: true
      freeRPG.farmingEXP: true
      freeRPG.fishingEXP: true
      freeRPG.archeryEXP: true
      freeRPG.beastMasteryEXP: true
      freeRPG.swordsmanshipEXP: true
      freeRPG.defenseEXP: true
      freeRPG.axeMasteryEXP: true
      freeRPG.repairEXP: true
      freeRPG.agilityEXP: true
      freeRPG.alchemyEXP: true
      freeRPG.smeltingEXP: true
      freeRPG.enchantingEXP: true
  freeRPG.useAbilities:
    description: allows the player to use all skill abilities
    default: true
    children:
      freeRPG.diggingAbility: true
      freeRPG.woodcuttingAbility: true
      freeRPG.miningAbility: true
      freeRPG.farmingAbility: true
      freeRPG.fishingAbility: true
      freeRPG.archeryAbility: true
      freeRPG.beastMasteryAbility: true
      freeRPG.swordsmanshipAbility: true
      freeRPG.defenseAbility: true
      freeRPG.axeMasteryAbility: true
  freeRPG.mainGUI:
    description: allows user to access main GUI with all skills
    default: true
  freeRPG.skillsGUI:
    description: allows user to access a skill's GUI (skill tree)
    default: true
  freeRPG.configGUI:
    description: allows user to access the configuration GUI
    default: true
  freeRPG.craftGUI:
    description: allows user to access the GUI that shows crafting recipes
    default: true
  freeRPG.confirmGUI:
    description: allows user to access the cofirmation GUI when refunding skills
    default: true
  freeRPG.info:
    decription: Allows the user to access the link to the info google document
    default: true
  freeRPG.help:
    description: Allows the user to see all FreeRPG commands
    default: true
  freeRPG.enchantItem:
    descriptin: Allows the user to access the enchant item command
    default: op
  freeRPG.leaderboard:
    description: Allows the user to access the leaderboard command, showing the user the top players in each skill
    default: true
  freeRPG.giveEXP:
    decription: Allows the user to give FreeRPG experience to any other player, including themselves
    default: op
  freeRPG.setLevel:
    description: Allows the user to set the FreeRPG skill level of any skill for any player
    default: op
  freeRPG.statReset:
    description: Allows the user to reset any FreeRPG skill of any player
    default: op
  freeRPG.diggingEXP:
    description: Allows player to get digging experience
    default: true
  freeRPG.woodcuttingEXP:
    description: Allows player to get woodcutting experience
    default: true
  freeRPG.miningEXP:
    description: Allows player to get mining experience
    default: true
  freeRPG.farmingEXP:
    description: Allows player to get farming experience
    default: true
  freeRPG.fishingEXP:
    description: Allows player to get fishing experience
    default: true
  freeRPG.archeryEXP:
    description: Allows player to get archery experience
    default: true
  freeRPG.beastMasteryEXP:
    description: Allows player to get beastMastery experience
    default: true
  freeRPG.swordsmanshipEXP:
    description: Allows player to get swordsmanship experience
    default: true
  freeRPG.defenseEXP:
    description: Allows player to get defense experience
    default: true
  freeRPG.axeMasteryEXP:
    description: Allows player to get axeMastery experience
    default: true
  freeRPG.repairEXP:
    description: Allows player to get repair experience
    default: true
  freeRPG.agilityEXP:
    description: Allows player to get agility experience
    default: true
  freeRPG.alchemyEXP:
    description: Allows player to get alchemy experience
    default: true
  freeRPG.smeltingEXP:
    description: Allows player to get smelting experience
    default: true
  freeRPG.enchantingEXP:
    description: Allows player to get enchanting experience
    default: true
  freeRPG.diggingAbility:
    description: allows the player to use the digging ability
    default: true
  freeRPG.woodcuttingAbility:
    description: allows the player to use the woodcutting ability
    default: true
  freeRPG.miningAbility:
    description: allows the player to use the mining ability
    default: true
  freeRPG.farmingAbility:
    description: allows the player to use the farming ability
    default: true
  freeRPG.fishingAbility:
    description: allows the player to use the fishing ability
    default: true
  freeRPG.archeryAbility:
    description: allows the player to use the archery ability
    default: true
  freeRPG.beastMasteryAbility:
    description: allows the player to use the beast mastery ability
    default: true
  freeRPG.swordsmanshipAbility:
    description: allows the player to use the swordsmanship ability
    default: true
  freeRPG.defenseAbility:
    description: allows the player to use the defense ability
    default: true
  freeRPG.axeMasteryAbility:
    description: allows the player to use the axe mastery ability
    default: true
  freeRPG.canRepair:
    description: allows player to use iron blocks to repair
    default: true
  freeRPG.canSalvage:
    description: allows player to use gold blocks to salvage
    default: true
  freeRPG.fish:
    description: players with this permission will use freeRPG's changed fishing system
    default: true



















  # Old commands
  #guiCommand:
  #  description: testing
  #skills:
  #  description: Opens skills GUI
  #spite:
  #  descriptions: Tells you what spite is good for.
  #globalGUI:
  #  description: Opens global skill tree
  #  aliases: [globalTree]
  #skillTreeGUI:
  #  description: Opens a skill tree GUI
  #  aliases: [skillTree]
  #craftingGUI:
  #  description: Opens crafting recipe
  #  aliases: [recipeGUI]
  #confirmationGUI:
  #  description: Opens confirmaiton GUI for refunding skill trees
  #  aliases: [confirmGUI]
  #configurationGUI:
  #  description: Opens configuration GUI for global settings
  #  aliases: [configGUI]
  #passiveSkillTreeGUI:
  #  description: Opens a passive skill tree GUI
  #  aliases: [passiveSkillTree]
  #giveEXP:
  #  description: gives player RPG EXP
  #  aliases:  [expGive]
  #setStatLevel:
  #  description: sets player RPG levels
  #  aliases: [levelSet]
  #statReset:
  #  description: resets specified stat
  #  aliases: [resetStat]
  #flintToggle:
  #  description: Toggles gravel 100% flint drops and normal drops
  #enchantItem:
  #  description: uses PseudoEnchanting to enchant item
  #speedToggle:
  #  description: Toggles permanent speed I buff
  #potionToggle:
  #  description: Toggles the level increase in potion buffs from the Poition Master Perk
  #flamePickToggle:
  #  description: Toggles auto smelting some blocks when broken with a pickaxe
  #grappleToggle:
  #  description: Toggles grappling hook fishing rod
  #hotRodToggle:
  #  description: Toggles catching cooked fish as opposed to raw, also changes a few fishing drops
  #veinMinerToggle:
  #  description: Toggles veins instantly mining
  #megaDigToggle:
  #  description: Toggles 3x3 breaking when using "Big Dig" Ability
  #statLeaders:
  #  description: Shows leaders of querried stat






















#  die:
#    description: Player dies.
#  heal:
#    description: Player is healed 2 hearts.
#    aliases: [healme,gainHP]
#  god:
#    description: Player becomes invincible.
#    aliases: [invincible]
#  printMessageFromConfig:
#    description: Prints a test message
#    alisases: [configPrint]
#  sendWord:
#    description: sends player a given word.
#  kill:
#    descriptions: Kills a nigga
#  vault:
#    description: Open a vault
#  guiCommand:
#    description: Creates  GUI
# woodcuttingGUI:
#    description: Opens woodcutting skill tree
#    aliases: [woodcuttingTree]
#  miningGUI:
#    description: Opens mining skill tree
#    aliases: [miningTree]
#  farmingGUI:
#    description: Opens farming skill tree
#    aliases: [farmingTree]
#  fishingUI:
#    description: Opens fishing skill tree
#    aliases: [fishingTree]
#  archeryGUI:
#    description: Opens archery skill tree
#    aliases: [archeryTree]
#  beastMasteryGUI:
#    description: Opens beast mastery skill tree
#    aliases: [beastMasteryTree]
#  swordsmanshipGUI:
#    description: Opens swordsmanship skill tree
#    aliases: [swordsmanshipTree]
#  defenseGUI:
#    description: Opens defense skill tree
#    aliases: [defenseTree]
#  axeMasteryGUI:
#    description: Opens axe mastery skill tree
#    aliases: [axeMasteryTree]
#  repairGUI:
#    description: Opens repair skill tree
#    aliases: [repairTree]
#  agilityGUI:
#    description: Opens agility skill tree
#    aliases: [agilityTree]
#  alchemyGUI:
#    description: Opens alchemy skill tree
#    aliases: [alchemyTree]
#  smeltingGUI:
#    description: Opens smelting skill tree
#    aliases: [smeltingTree]
#  enchantingGUI:
#    description: Opens enchanting skill tree
#    aliases: [enchantingTree]